- id: fuel_plugin_authzforce-post-deployment-sh
  type: shell
  role: [AuthZForce]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    cmd: bash deploy.sh
    retries: 3
    interval: 20
    timeout: 180

- id: AuthZForce
  type: group
  role: [AuthZForce]
  requires: [computer]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: parallel
